name: Type check with mypy

on: [push, pull_request]

jobs:
  typecheck:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install -U pip setuptools
        if [ -n "$GITHUB_HEAD_REF" ]; then
          export GHBRANCH="${GITHUB_HEAD_REF#refs/heads/}"
        else
          export GHBRANCH="${GITHUB_REF#refs/heads/}"
        fi
        echo "HEAD: ${GHBRANCH} (${GITHUB_REF}, ${GITHUB_HEAD_REF})"
        # Use the same branch (if exists) for the backend.ai-common installation
        set +e
        git ls-remote --heads 'https://github.com/lablup/backend.ai-client-py' | grep -q "refs/heads/${GHBRANCH}"
        if [ $? -eq 0 ]; then
          sed -i "s%\(backend.ai-client-py\)@master%\1@${GHBRANCH}%" requirements/typecheck.txt
        fi
        git ls-remote --heads 'https://github.com/lablup/backend.ai-common' | grep -q "refs/heads/${GHBRANCH}"
        if [ $? -eq 0 ]; then
          sed -i "s%\(backend.ai-common\)@master%\1@${GHBRANCH}%" requirements/typecheck.txt
        fi
        set -e
        python -m pip install -U -r requirements/typecheck.txt
    - name: Type check with mypy
      run: |
        if [ "$GITHUB_EVENT_NAME" == "pull_request" -a -n "$GITHUB_HEAD_REF" ]; then
          echo "(skipping matchers for pull request from local branches)"
        else
          echo "::add-matcher::.github/workflows/mypy-matcher.json"
        fi
        python -m mypy --no-color-output src/ai/backend || exit 0
